# Generated by Django 4.2.4 on 2023-08-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_postblog_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/%Y/%m/%d'),
        ),
    ]
