# Generated by Django 4.2.4 on 2023-08-29 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postblog_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postblog',
            name='is_pubished',
        ),
    ]
