# Generated by Django 4.2.4 on 2023-09-04 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_postblog_is_pubished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.category'),
        ),
    ]
