# Generated by Django 4.2.4 on 2023-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postblog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
