name: Coverage

on: [push]

jobs:
  upload-coverage:
    name: Upload Coverage to Codecov
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up environment
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo "$ENV_FILE" > .env

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./htmlcov/index.html
          token: ${{ secrets.CODECOV_TOKEN }}