---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test, Lint, and Coverage
    runs-on: ubuntu-20.04
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: python manage.py test 

      - name: Lint
        run: flake8
        