name: Checks

on: [push]

jobs:
  test-lint:
    name: Test, Lint, and Coverage
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up environment
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        run: echo "$ENV_FILE" > .env

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Test coverage
        run: coverage run -m pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}